### ISSUE TITLE
Security Audit for Vesting contracts

### ISSUE THREAD

**Issue by rstormsf** [JoinColony/colonyToken#9]
I think your vesting contract looks pretty good, so I'd like to know if it was ever audited because I could only find Dapphub audit which doesn't include Vesting contract.

I also wasn't able to find CLNY token on ethereum mainnet deployed to find any vesting contracts on the network.

Would you mind to assure me that someone has used the code in production.

the only token with 0 total supply I could find is this:
https://etherscan.io/address/0x06441deaf11d60d77e5e42d4f644c64ca05c2fce#readContract

**Comment by elenadimitrova** [comment]
That is indeed the right CLNY token address. We will be minting soon so if you want to see this "in action" hold off for a few more days.

Oleksii Matiyasevych did a review for us which issues were fixes in #5 

The Vesting contract was deployed here `0x670947F402410F30654660D7E916312FF3190f68` however that will be redeployed later today or tomorrow with a new MultiSig address initialise parameter to match what the business wants.
